name: Merging CI

on:
  pull_request_target:
    types: [enqueued]
  merge_group:
    types: [checks_requested]

jobs:
  append-committer-signed-off-by:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          scripts/append-committer-signed-off-by.sh
