name: Merging CI

on:
  pull_request:
  merge_group:

jobs:
  append-committer-signed-off-by:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          scripts/append-committer-signed-off-by.sh
